version: 2.1

jobs:
  snyk-test:
    docker:
      - image: circleci/node:14  # Node.js Docker image
    steps:
      - checkout  # Check out your code
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Snyk locally
          command: npm install snyk
      - run:
          name: Authenticate Snyk
          command: npx snyk auth $SNYK_TOKEN
      - run:
          name: Run Snyk test
          command: npx snyk test

workflows:
  version: 2
  test:
    jobs:
      - snyk-test